version: '2.4'
services:
  npm_registry:
    build:
      context: npm_registry
  reservations-backend:
    build:
      context: reservations/backend
      target: prod
    depends_on:
      - npm_registry
  