version: '2.4'
services:
  
  reservations-backend:
    build:
      target: prod

  system-tests:
    depends_on:
      - reservations-backend
      - reservations-db
    build:
      context: system-test

  