version: '2.4'
services:

  reservations_backend:
    build:
      target: prod
    
  bdd-tests:
    depends_on:
      - reservations_backend
      - reservations_database
    build:
      context: bdd-tests
  