version: '2.4'
services:
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    # volumes:
    #   - ./frontend/src:/usr/app/src:rw
  backend:
    build:
      context: backend
    ports:
      - 8080:8080
    # volumes:
    #   - ./backend/src:/usr/app/src:rw