version: '2.4'
services:
  
  reservations_backend:
    build:
      target: prod

  system-tests:
    depends_on:
      - reservations_backend
      - reservations_database
    build:
      context: system-test

  