/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Data to be provided to create a reservation
 */
export interface Reservation {
  id: string;
  customer: {
    name: string;
    email: string;
  };
  reservation: {
    checkin: string;
    checkout: string;
    numAdults: number;
    numChildren: number;
    roomType: string;
    specialRequests?: string;
  };
  source: {
    origin: string;
    reservationId: string;
  };
}
