version: '2.4'
services:
  reservations_backend:
    depends_on:
      - reservations_database
      - broker
    build:
      context: reservations-backend
      target: prod
    ports:
      - 3000:3000
