version: '2.4'
services:
  reservations-backend:
    depends_on:
      - reservations-db
      - broker
      - reservations-event-publisher
    build:
      context: reservations/backend
      target: prod
    ports:
      - 3000:3000

  reservations-event-publisher:
    depends_on:
      - reservations-db
      - broker
    build:
      context: reservations/event-publisher
      target: prod

  reservations-frontend:
    depends_on:
      - reservations-backend
    build:
      context: reservations/frontend
      target: prod
    ports:
      - 4000:4000
