version: '2.4'
services:
  reservations-backend:
    depends_on:
      - reservations-db
      - broker
    build:
      context: reservations/backend
      target: prod
    ports:
      - 3000:3000

