version: '2.4'
services: 
  # Overwrites the default values of backend - prod.
  reservations-backend:
    build:
      target: dev
    volumes:
      - ./backend/src:/app/src

  reservations-frontend:
    build:
      target: dev
    volumes:
      - ./frontend/src:/app/src

  