name: Basic check for Ruteho
on: [push]
jobs:
  Check-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build backend
        run: docker build backend/