name: pr-check
on:
  - pull_request

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  cancel-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  reservations-backend-unit-tests:
    name: reservations-backend-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unit tests
        run: docker build reservations/backend --target test
  reservations-bdd-tests:
    name: reservations-bdd-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: BDD Tests
        run: make test-bdd
  reservations-system-tests:
    name: reservations-system-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: System Tests
        run: make test-system
  all-checks-passed:
    name: all-checks-passed
    runs-on: ubuntu-latest
    needs:
      [
        reservations-backend-unit-tests,
        reservations-system-tests,
        reservations-bdd-tests,
      ]
    steps:
      - name: Print
        run: echo "All Succeeded"
