name: Basic check for Ruteho
on:
  - pull_request
jobs:
  Check-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: System Tests
        run: docker compose -f docker-compose-system-test.yaml up --exit-code-from system-test