name: pr-check
on:
  - pull_request
jobs:
  BackendSystemTests:
    name: backend-system-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unit tests
        run: docker build backend --target test
      - name: System Tests
        run: make test-system
      - name: BDD Tests
        run: make test-bdd
