name: pr-check
on:
  - pull_request
jobs:
  cancel-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  sleep:
    name: sleep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: sleep 100
  backend-unit-tests:
    name: backend-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unit tests
        run: docker build backend --target test
  backend-bdd-tests:
    name: backend-bdd-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: BDD Tests
        run: make test-bdd
  backend-system-tests:
    name: backend-system-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: System Tests
        run: make test-system
  all-checks-passed:
    name: all-checks-passed
    runs-on: ubuntu-latest
    needs: [backend-unit-tests, backend-system-tests, backend-bdd-tests]
    steps:
      - name: Print
        run: echo "All Succeeded"
